schema: "classroom50/repo-config/v1"
classroom: "ds212"
assignment: "portfolio"
owner:
  username: "Rifegu"
  id: 157092735
  accepted_at: "2026-09-09T03:44:11Z"
source:
  owner: "mac-ds212-f26"
  owner_id: 323652586
  repo: "portfolio-template"
  branch: "main"
